### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kalbermattenm** [sitn/Historisation#3]
Ne pourrait-on pas monter la doc dans le wiki ?

(même s'il n'y a pas grand-chose comme doc...)

**Comment by pabstsy** [comment]
suis en train de la finaliser. Stéphane proposait de mettre un exemple avec copies d'écran

**Comment by kalbermattenm** [comment]
Super ! Merci !!!

**Comment by pabstsy** [comment]
Le wiki est réalisé !

**Comment by voisardf** [comment]
👍

**Comment by kalbermattenm** [comment]
Merci !!!
